------------------------------make flower_seasonS-----------------------------------------------
call next value for hibernate_sequence;
insert into season values (0, '봄');
call next value for hibernate_sequence;
insert into season values (1, '여름');
call next value for hibernate_sequence;
insert into season values (2, '가을');
call next value for hibernate_sequence;
insert into season values (3, '겨울');
------------------------------make COLOR-------------------------------------------------
call next value for hibernate_sequence;
insert into color values (1, '빨강');
call next value for hibernate_sequence;
insert into color values (2, '노랑');
call next value for hibernate_sequence;
insert into color values (3, '파랑');
call next value for hibernate_sequence;
insert into color values (4, '보라');
call next value for hibernate_sequence;
insert into color values (5, '분홍');
call next value for hibernate_sequence;
insert into color values (6, '하얀');
call next value for hibernate_sequence;
insert into color values (7, '주황');

-------------------------- make keyword ----------------------------------------------
call next value for hibernate_sequence;
insert into keyword values (1, '사랑');
call next value for hibernate_sequence;
insert into keyword values (0, '희망');
call next value for hibernate_sequence;
insert into keyword values (2, '우정');
call next value for hibernate_sequence;
insert into keyword values (3, '기쁨');
call next value for hibernate_sequence;
insert into keyword values (4, '감사');
call next value for hibernate_sequence;
insert into keyword values (5, '성취');
call next value for hibernate_sequence;
insert into keyword values (6, '축하');
call next value for hibernate_sequence;
insert into keyword values (7, '행복');
call next value for hibernate_sequence;
insert into keyword values (8, '축복');
call next value for hibernate_sequence;
insert into keyword values (9, '자랑');
call next value for hibernate_sequence;
insert into keyword values (10,'걱정');
call next value for hibernate_sequence;
insert into keyword values (11, '슬픔');
call next value for hibernate_sequence;
insert into keyword values (12, '위로');
call next value for hibernate_sequence;
insert into keyword values (13, '시작');
call next value for hibernate_sequence;
insert into keyword values (14, '존경');
call next value for hibernate_sequence;
insert into keyword values (15, '응원');
call next value for hibernate_sequence;
insert into keyword values (16, '재물');
call next value for hibernate_sequence;
insert into keyword values (17, '분노');
call next value for hibernate_sequence;
insert into keyword values (18, '질투');
call next value for hibernate_sequence;
insert into keyword values (19, '최선');
call next value for hibernate_sequence;
insert into keyword values (20, '건강');
call next value for hibernate_sequence;
insert into keyword values (21, '아름다움');
call next value for hibernate_sequence;
insert into keyword values (22, '유혹');
call next value for hibernate_sequence;
insert into keyword values (23, '기억');
call next value for hibernate_sequence;
insert into keyword values (24, '추억');
call next value for hibernate_sequence;
insert into keyword values (25, '신비');
call next value for hibernate_sequence;
insert into keyword values (26, '경고');
call next value for hibernate_sequence;
insert into keyword values (27, '불변');